services:
  db:
    image: postgres:15.2
    container_name: carrentalhub-db
    restart: always
    env_file:
      - ../Backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build:
       context: ../Backend
       dockerfile: docker/Dockerfile
    container_name: carrentalhub-backend
    restart: always
    env_file:
      - ../Backend/.env
    environment:
      APP_ENV: prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:8085"
    volumes:
      - ../Backend/logs:/app/logs

  stats:
    build:
      context: ../Stats  # La directory in cui si trova il Dockerfile per il modulo Python
      dockerfile: docker/Dockerfile
    container_name: carrentalhub-stats
    restart: always
    env_file:
      - ../Backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5005:5005"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ../Stats/static/images:/app/static/images

volumes:
  pgdata: